import React, { useState } from "react";
import Select from "react-select";
import "./localidades.css";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";

const data = {
  "Buenos Aires": [
    "11 de septiembre",
    "Abasto",
    "Acassuso",
    "Adrogué",
    "Aldo Bonzi",
    "Alejandro Korn",
    "Almirante Brown",
    "Angel Etcheverry",
    "Arana",
    "Área de promoción del triángulo",
    "Arturo Seguí",
    "Arrecifes",
    "Avellaneda",
    "Azul",
    "Bahía Blanca",
    "Bancalari",
    "Banfield",
    "Baradero",
    "Barrio San José",
    "Beccar",
    "Belén de Escobar",
    "Bella Vista",
    "Benavídez",
    "Berazategui",
    "Berisso",
    "Bernal",
    "Bilingurst",
    "Bosques",
    "Boulogne",
    "Burzaco",
    "Campana",
    "Campo de Mayo",
    "Canning",
    "Capital Federal",
    "Carapachay",
    "Carlos Keen",
    "Carmen de Areco",
    "Caseros",
    "Castelar",
    "Chilavert",
    "Chivilcoy",
    "Churruca",
    "City Bell",
    "Ciudad Evita",
    "Ciudad Jardín",
    "Ciudad Madero",
    "Ciudadela",
    "Claypole",
    "Cortines",
    "Cruce de Florencio Varela",
    "Crucesita",
    "Del Viso",
    "Dock Sud",
    "Don Bosco",
    "Don Orione",
    "Don Torcuato",
    "El Jaguel",
    "El Libertador",

    "El Palomar",
    "El Pato",
    "El Peligro",
    "El Talar",
    "El Talar de Pacheco",
    "El Triángulo",
    "Ensenada",
    "Escobar",
    "Ezeiza",
    "Ezpeleta",
    "Fátima",
    "Florencio Varela",
    "Florida Este",
    "Florida Oeste",
    "Francisco Álvarez",
    "Garín",
    "Garín - Parque Industrial",
    "General Daniel Cerri",
    "General Pacheco",
    "General Rodríguez",
    "General San Martín",
    "Gerli",
    "Glew",
    "Grand Bourg",
    "Guernica",
    "Guillermo E. Hudson",
    "Haedo",
    "Hurlingham",
    "Ingeniero Alán",
    "Ingeniero Maschwitz",
    "Ingeniero Pablo Nogues",
    "Ingeniero White",
    "Isidro Casanova",
    "Ituzaingó",
    "Jauregui",
    "José C. Paz",
    "José Ingenieros",
    "José Leon Suarez",
    "José Mármol",
    "Juan María Gutierrez",
    "Junín",
    "La Cumbre",
    "La Emilia",
    "La estrella",
    "La Lucila",
    "La Matanza",
    "La Plata",
    "La Reja",
    "La Tablada",
    "Lanús",
    "Lanús Oeste",
    "Lavallol",
    "Lima",
    "Lisandro Olmos",
    "Loma Hermosa",
    "Loma Verde",
    "Lomas de Zamora",
    "Lomas del Mirador",
    "Longchamps",
    "Los Cardales",
    "Los Hornos",
    "Los Polvorines",
    "Los Troncos del Talar",
    "Luis Guillón",
    "Luján",
    "Manuel Alberti",
    "Manuel B. Gonnet Estafeta",
    "Manzanares",
    "Mar del Plata",
    "Martín Coronado",
    "Martínez",
    "Matheu",
    "Melchor Romero",
    "Mercedes",
    "Merlo",
    "Microcentro - Caba",
    "Miguelete",
    "Ministro Rivadavia",
    "Monte Chingolo",
    "Monte Grande",
    "Moreno",
    "Morón",
    "Munro",
    "Muñiz",
    "Nordelta",
    "Olavarría",
    "Olivos",
    "open Door",
    "Pablo Podestá",
    "Paso del Rey",
    "Pereyra",
    "Pergamino",
    "Pilar",
    "Piñeyro",
    "Plátanos",
    "Presidente Derqui",
    "Punta Alta",
    "Punta Lara",
    "Quilmes",
    "Rafael Calzada",
    "Ramallo",
    "Ramos Mejías",
    "Ranelagh",
    "Remedios de Escalada",
    "Remedios de Escalada de San Martín",
    "Ricardo Rojas",
    "Rincón de Milberg",
    "Ringuelet",
    "Salta",
    "Saenz Peña",
    "San Andrés",
    "San Andrés de Giles",
    "San Antonio de Areco",
    "San Antonio de Padua",
    "San Fernando",
    "San Francisco Solano",
    "San Isidro",
    "San Justo",
    "San Martín",
    "San Miguel",
    "San Nicolás",
    "San Pedro",
    "San Vicente",
    "Santos Lugares",
    "Sarandí",
    "Sierra Chica",
    "Sierras Bayas",
    "Sourigues",
    "Tablada",
    "Tandil",
    "Tapiales",
    "Temperley",
    "Tigre",
    "Todd",
    "Tolosa",
    "Tortuguitas",
    "Tres Arroyos",
    "Tres de Febrero",
    "Tristán Suárez",
    "Turdera",
    "Valentín Alsina",
    "Vicente López",
    "Victoria",
    "Villa Adelina",
    "Villa Alfredo Fortabat",
    "Villa Astolfi",
    "Villa Ballester",
    "Villa Bosch",
    "Villa Celina",
    "Villa Centenario",
    "Villa Domínico",
    "Villa Elisa",
    "Villa España",
    "Villa Insuperable",
    "Villa la Florida",
    "Villa Luzuriaga",
    "Villa Lynch",
    "Villa Madero",
    "Villa Maipú",
    "Villa Martelli",
    "Villa Raffo",
    "Villa Ramallo",
    "Villa Rosa",
    "Villa Santos Tesei",
    "Villa Sarmiento",
    "Villa Tesei",
    "Villeres",
    "Viña",
    "Virreyes",
    "Wilde",
    "Zárate",
  ],
  Catamarca: ["Belén", "Andalgala", "San Isidro", "Valle Viejo"],
  Chaco: [
    "Barranqueras",
    "Capitán Solari",
    "Charata",
    "Colonia Elisa",
    "Colonia Juan José Castelli",
    "Colonias Unidas",
    "Coronel Du Graty",
    "Corzuela",
    "Fontana",
    "General José de San Martín",
    "General Pinedo",
    "General Vedia",
    "La Leonesa",
    "Las Breñas",
    "Las Garcitas",
    "Las Palmas",
    "Machagai",
    "Pampa Almirón",
    "Pampa del Indio",
    "Parque Industrial Puerto Tirol",
    "Presidencia Roque Saenz Peña",
    "Puerto Vilelas",
    "Quitilipi",
    "Resistencia",
    "Santa Sylvina",
    "Villa Ángela",
  ],
  Chubut: [
    "Comodoro Rivadavia",
    "Esquel",
    "Gaiman",
    "Lago Puelo",
    "Puerto Madryn",
    "Rada Tilly",
    "Rawson",
    "Sarmiento",
    "Trelew",
    "Trevelin",
  ],
  Córdoba: [
    "Alcira Gigena",
    "Almafuerte",
    "Alta Gracia",
    "Atos Pampa",
    "Amboy",
    "Anisacate",
    "Arroyito",
    "Arroyo Cabral",
    "Ballesteros",
    "Ballesteros Sud",
    "Bell Ville",
    "Berrotarán",
    "Bialet Massé",
    "Brinckmann",
    "Camilo Aldao",
    "Capilla del Monte",
    "Carnerillo",
    "Casa Grande",
    "Charbonier",
    "Colonia Caroya",
    "Córdoba",
    "Coronel Baigorria",
    "Corralito",
    "Cosquín",
    "Costa Sacate",
    "Cruz Alta",
    "Cruz del Eje",
    "Cura Brochero",
    "Dalmacio Vélez Sarsfield",
    "Dean Funes",
    "Despeñaderos",
    "Dolores",
    "El Torreon",
    "Elena",
    "Embalse",
    "Estación General Paz",
    "Ferreyra",
    "General Baldisera",
    "General Cabrera",
    "General Deheza",
    "General Fotheringham",
    "Guiñazú",
    "Hernando",
    "Huerta Grande",
    "Inriville",
    "Isla Verde",
    "James Craik",
    "Jesús María",
    "Juarez Celman",
    "Justiniano Posse",
    "La Calera",
    "La Carlota",
    "La Cruz",
    "La Cumbre",
    "La Cumbrecita",
    "La Falda",
    "La Laguna",
    "La Perla",
    "Laguna Larga",
    "Laborde",
    "Las Bajadas",
    "Las Cañitas",
    "Las Higueras",
    "Las Perdices",
    "Las Rabonas",
    "Las Varillas",
    "Leones",
    "Los Boulevares",
    "Los Cocos",
    "Los Cóndores",
    "Los Molinos",
    "Los Reartes",
    "Los Surgentes",
    "Lozada",
    "Luque",
    "Luca",
    "Malagueño",
    "Malvinas Argentinas",
    "Manfredi",
    "Marcos Juárez",
    "Mendiolaza",
    "Mi Granja",
    "Mina Clavero",
    "Monte Buey",
    "Monte Leña",
    "Monte Maíz",
    "Monte Ralo",
    "Montecristo",
    "Morrison",
    "Morteros",
    "Noetinger",
    "Nono",
    "Oncativo",
    "Ordoñez",
    "Pampayasta Norte",
    "Pampayasta Sur",
    "Pascanas",
    "Pasco",
    "Pedro E. Vivas",
    "Potrero de Garay",
    "Río Cuarto",
    "Rio Primero",
    "Río Segundo",
    "Río Tercero",
    "San Agustín",
    "San Francisco",
    "San Ignacio",
    "San Juan",
    "San Marcos Sud",
    "San Roque",
    "Santa María de Punilla",
    "Santa Mónica",
    "Santa Rosa de Calamuchita",
    "Santiago Temple",
    "Sinsacate",
    "Tancacha",
    "Toledo",
    "Tránsito",
    "Ticino",
    "Unquillo",
    "Valle Hermoso",
    "Villa Allende",
    "Villa Alpina",
    "Villa Amancay",
    "Villa Anisacate",
    "Villa Ascasubi",
    "Villa Carlos Paz",
    "Villa Ciudad de América",
    "Villa Ciudad Parque",
    "Villa de Soto",
    "Villa del Dique",
    "Villa del Rosario",
    "Villa Dolores",
    "Villa el Corcovado",
    "Villa Esquiú",
    "Villa General Belgrano",
    "Villa Giardino",
    "Villa La Bolsa",
    "Villa las Rosas",
    "Villa la Serranita",
    "Villa los Aromos",
    "Villa María",
    "Villa Nueva",
    "Villa Rumipal",
    "Villa San Nicolás",
    "Villa Santa Rosa",
    "Villa Soldati",
    "Wenceslao Escalante",
    "Yacanto de Calamuchita",
    "Yocsina",
  ],
  Corrientes: [
    "Colonia Carolina",
    "Corrientes",
    "Goya",
    "Lavalle",
    "Paso de los Libres",
    "Santa Lucía",
  ],
  "Entre Ríos": [
    "Aldea Protestante",
    "Aldea Valle María",
    "Aranguren",
    "Camps",
    "Colón",
    "Concepción del Uruguay",
    "Concordia",
    "Crespo",
    "Diamante",
    "General Ramírez",
    "Gualeguaychú",
    "Hernández",
    "Paraná",
    "San José",
    "Villa Elisa",
    "Villa Libertador San Martín",
  ],
  Formosa: [
    "Clorinda",
    "El Colorado",
    "Formosa",
    "Ibarreta",
    "Pirane",
    "Villa Dos Trece",
  ],
  Jujuy: [
    "Alto Comedero",
    "El Carmen",
    "Fraile Pintado",
    "La Quiaca",
    "Ledesma",
    "Libertador General San Martín",
    "Monterrico",
    "Palpalá",
    "Perico",
    "San Antonio",
    "San Pedro",
    "San Salvador de Jujuy",
  ],
  "La Pampa": [
    "Caleufu",
    "Colonia Baron",
    "Eduardo Castex",
    "Intendente Alvear",
    "Pico",
    "Quemu Quemu",
    "Rancul",
    "Realico",
    "Santa Rosa",
  ],
  "La Rioja": ["Chamical", "Chilecito", "La Rioja"],
  Mendoza: ["Consultar Localidades"],
  Misiones: ["Posadas", "Villafañe"],
  Neuquén: [
    "Centenario",
    "Junín de los Andes",
    "Neuquén",
    "Piedra del Águila",
    "Plottier",
    "San Martín de los Andes",
    "Villa la Angostura",
    "Zapala",
  ],
  "Río Negro": [
    "Allen",
    "Cervantes",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "Coronel Belisle",
    "El Bolsón",
    "Fernández Oro",
    "General Conesa",
    "General Roca",
    "Ing. L.A. Huergo",
    "Lamarque",
    "Las Grutas",
    "Luis Beltrán",
    "Río Colorado",
    "San Antonio Oeste",
    "San Carlos de Bariloche",
    "Sierra Grande",
    "Viedma",
    "Villa Regina",
  ],
  "San Luis": ["Consultar Localidades"],
  "San Juan": ["Consultar Localidades"],
  "Santa Cruz": ["Perito Moreno", "Las Heras", "Pico Truncado", "Río Gallegos"],
  "Santa Fe": [
    "Alvear",
    "Arequito",
    "Armstrong",
    "Arroyo Seco",
    "Arteaga",
    "Avellaneda",
    "Calchaquí",
    "Clorinda",
    "Cañada de Gómez",
    "Capitán Bermúdez",
    "Carcarañá",
    "Carlos Pellegrini",
    "Casilda",
    "Ceres",
    "Chabás",
    "Correa",
    "El Trébol",
    "Empalme Villa Constitución",
    "Esperanza",
    "Fighiera",
    "Firmat",
    "Franck",
    "Fray Luis Beltrán",
    "Frontera",
    "Funes",
    "Gálvez",
    "General Lagos",
    "Gessler",
    "Gobernador Crespo",
    "Granadero Baigorria",
    "Guadalupe Norte",
    "Ibarlucea",
    "La Criolla",
    "Las Parejas",
    "Las Rosas",
    "Las Toscas",
    "Las Tunas",
    "Los Molinos",
    "Los Nogales",
    "Margarita",
    "María Juana",
    "María Susana",
    "Parque Industrial Pérez",
    "Pavón",
    "Pedro Gómez Cello",
    "Perez",
    "Piamonte",
    "Pueblo Esther",
    "Puerto General San Martín",
    "Rafaela",
    "Reconquista",
    "Ricardone",
    "Roldán",
    "Rosario",
    "San Agustín",
    "San Antonio de Obligado",
    "San Carlos Centro",
    "San Carlos Norte",
    "San Carlos Sur",
    "Sanford",
    "San Javier",
    "San Jerónimo del Sauce",
    "San Jerónimo Norte",
    "San Jerónimo Sur",
    "San Jorge",
    "San José de la Esquina",
    "San Justo",
    "San Lorenzo",
    "Santa Fe",
    "Santo Tomé",
    "Sauce Viejo",
    "Soldini",
    "Sunchales",
    "Tacuarendí",
    "Tostado",
    "Venado Tuerto",
    "Vera",
    "Vera y Pintado",
    "Villa Constitución",
    "Villada",
    "Villa Gobernador Gálvez",
    "Villa Ocampo",
  ],
  Salta: [
    "Aguaray",
    "Campo Quijano",
    "Campo Santo",
    "Cerrillos",
    "Cobos",
    "Coronel Moldes",
    "El Bordo",
    "El Carmen",
    "El Carril",
    "El Quebrachal",
    "El Tabacal",
    "Embarcación",
    "General Guemes",
    "General Mosconi",
    "Hipólito Yrigoyen",
    "Joaquín V. González",
    "La Merced",
    "Las Lajitas",
    "Lumbreras",
    "Metán",
    "Orán",
    "Pichanal",
    "Rosario de Lerma",
    "Salta",
    "Salvador Mazza",
    "San Lorenzo",
    "San Luís",
    "Tartagal",
    "Vaqueros",
    "Villa Esmeralda",
  ],
  "Santiago del Estero": [
    "Añatuya",
    "Bandera",
    "Juríes",
    "La Banda",
    "Quimilí",
    "Santiago del Estero",
  ],
  "Tierra del Fuego": ["Río Grande", "Tolhuin", "Ushuaia"],
  Tucumán: [
    "Aguilar",
    "Alberdi",
    "Alderetes",
    "Banda del Río Salí",
    "Cevil Redondo",
    "Concepción",
    "El Manantial",
    "Famaillá",
    "La Banda (del Río Salí)",
    "Las Talitas",
    "Lastenia",
    "Los Pocitos",
    "Lules",
    "Manantiales",
    "Monteros",
    "San Andrés",
    "San José",
    "San Miguel de Tucumán",
    "San Pablo",
    "Soldado Maldonado",
    "Tafí Viejo",
    "Villa Carmela",
    "Villa Mariano Moreno",
    "Yerba Buena",
  ],
};

const estilosPersonalizados = {
  control: (base) => ({
    ...base,
    minHeight: "35px", // Ajusta a la altura deseada
    boxShadow: "none",
    "&:hover": {
      borderColor: "gray", // Ajusta a tu color preferido
    },
  }),
  valueContainer: (base) => ({
    ...base,
    padding: "0 6px",
  }),
  indicatorsContainer: (base) => ({
    ...base,
    height: "35px", // Ajusta a la altura deseada
  }),
  dropdownIndicator: (base) => ({
    ...base,
    padding: "0 8px",
  }),
  clearIndicator: (base) => ({
    ...base,
    padding: "0 8px",
  }),
};

const ProvinciasLocalidades = () => {
  const [selectedProvincia, setSelectedProvincia] = useState(null);
  const [selectedLocalidad, setSelectedLocalidad] = useState(null);

  const opcionesProvincias = Object.keys(data).map((provincia) => ({
    value: provincia,
    label: provincia,
  }));

  const opcionesLocalidades =
    selectedProvincia && data[selectedProvincia.value]
      ? data[selectedProvincia.value].map((localidad) => ({
          value: localidad,
          label: localidad,
        }))
      : [];

  const manejarCambioProvincia = (opcionSeleccionada) => {
    setSelectedProvincia(opcionSeleccionada);
    setSelectedLocalidad(null);
  };

  const manejarCambioLocalidad = (opcionSeleccionada) => {
    setSelectedLocalidad(opcionSeleccionada);
  };

  const obtenerLinkWhatsApp = () => {
    const provincia = selectedProvincia?.label || "";
    const localidad = selectedLocalidad?.label || "";
    const mensaje = `Hola. Me gustaria pedir cotizacion para ${localidad} en ${provincia}.`;
    return `https://wa.me/5493517078383?text=${encodeURIComponent(mensaje)}`;
  };

  return (
    <div className="contenedorTotal">
      <div className="contenedorTitulo">
        <img
          className="nuestrosDestinos"
          src="https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Nuestros%20destinos-04.png?alt=media&token=2e5a8bd8-328e-4d8d-bd59-818ec2120fb9"
          alt=""
        />
      </div>
      <div className="provincias-localidades">
        <h1 className="destinosH1">Llegamos a más de 700 localidades</h1>
        <div className="contenedorLocalidades">
          <img
            className="mapaImg"
            src="https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/mapa.png?alt=media&token=3f258575-b82e-43b5-aa96-a6e086cf983a"
            alt=""
          />
          <div className="contenedorLabel">
            <div>
              <label className="textosLabel" htmlFor="provincia">
                Provincia:{" "}
              </label>
              <Select
                id="provincia"
                value={selectedProvincia}
                onChange={manejarCambioProvincia}
                options={opcionesProvincias}
                className="form-select"
                classNamePrefix="react-select"
                styles={estilosPersonalizados}
              />
            </div>
            <div>
              <label className="textosLabel" htmlFor="localidad">
                Localidad:{" "}
              </label>
              <Select
                id="localidad"
                value={selectedLocalidad}
                onChange={manejarCambioLocalidad}
                options={opcionesLocalidades}
                className="form-select"
                classNamePrefix="react-select"
                styles={estilosPersonalizados}
                isDisabled={!selectedProvincia}
              />
            </div>
            <div>
              {selectedProvincia && selectedLocalidad && (
                <p className="textoSeleccionado">
                  Seleccionaste la localidad de {selectedLocalidad.label} en la
                  provincia de {selectedProvincia.label}.
                </p>
              )}
            </div>

            <div className="contenedorTitulo3">
              <a
                className="linkPedi"
                href={obtenerLinkWhatsApp()}
                target="_blank"
                rel="noopener noreferrer"
              >
                <img
                  className="cotizacion"
                  src="https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Pedi%20tu%20cotizacion%20azul-04.png?alt=media&token=ac90e20c-50cd-45e1-b265-e75fa02bb329"
                  alt=""
                />
                <WhatsAppIcon className="whatsappIcon" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProvinciasLocalidades;
