export let serviciosMock = [
  {
    id: 1,
    title: "Envíos en 24 horas",
    description: "• Córdoba - Buenos Aires / Buenos Aires - Córdoba en 24hs.",
    description2: "• Frecuencia asegurada a más de 700 localidades del país.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/24%20hs.png?alt=media&token=36b40ab5-a4ef-4d98-ae96-a819f1d88292",
  },
  {
    id: 2,
    title: "Ecommerce",
    description: "• Hacemos crecer tu emprendimiento.",
    description2: "• Paqueteria desde 100gr hasta 50kg.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",

    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Ecommerce.png?alt=media&token=5047ca59-d8b0-42f7-9001-6e12b81ce2e6",
  },
  {
    id: 3,
    title: "Cargas Completas",
    description: "• Equipos completos - 26 pallets.",
    description2: "• Chasis, acomplado, semiremolque y sider",
    description3: "• Entregas directas a clientes e interplantas",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Cargas%20Completas.png?alt=media&token=d0ee3223-e148-40c6-85b6-372f5d2fa1ed",
  },
  {
    id: 4,
    title: "Cargas Peligrosas",
    description:
      "• Conductores habilitados para transporte de cargas peligrosas.",
    description2:
      "• Vehículos con habilitación para transporte de cargas peligrosas.",
    description3:
      "• Agroquímicos, pinturas, químicos, inflamables, tóxicos y corrosivos.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Cargas%20Peligrosas.png?alt=media&token=7ed907fb-f3c2-4228-b1de-8ecdcd8bb64b",
  },
  {
    id: 5,
    title: "Desconsolidado de Contenedores",
    description: "• Retiro de contenedor en puerto o aduana.",
    description2: "• Desconsolidado y palletizado de mercadería.",
    description3: "• Devolución de contenedor.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Desconsilidado%20de%20contenedores.png?alt=media&token=5b991f25-8395-4d2a-9e7f-1c5878c351a5",
  },
  {
    id: 6,
    title: "Servicio Puerta a Puerta",
    description: "• Retiro a domicilio en Córdoba y Buenos Aires.",
    description2: "• Entrega a domicilio en mas de 700 localidades.",

    description3: "• Carga asegurada.",
    description4: "• Seguimiento online de tu envío.",

    description5: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Servicio%20Puerta%20a%20Puerta.png?alt=media&token=5c917d42-17e4-4da8-9214-da8a8570b262",
  },
  {
    id: 7,
    title: "Warehouse",
    description: "• Almacenamiento de mercadería.",
    description2: "•Recepción de mercadería.",
    description3: "• Envío parcial de mercadería.",
    description4: "• Gestión de inventario.",
    description5: "• Fraccionamiento y repalletizado.",
    description6: "• Carga asegurada.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/Warehouse.png?alt=media&token=436d1023-3325-4b33-a7b8-391703baa020",
  },
  // {
  //   id: 8,
  //   title: "Envíos a todo el país",
  //   description: "• Almacenamiento de mercadería.",
  //   description2: "•Recepción de mercadería.",
  //   description3: "• Envío parcial de mercadería.",
  //   description4: "• Gestión de inventario.",
  //   description5: "• Fraccionamiento y repalletizado.",
  //   description6: "• Carga asegurada.",
  //   description7: "• Atención humana y personalizada.",
  //   img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/mapa%20blanco.png?alt=media&token=299e5086-aae8-4787-a70b-117e7857dc3b",
  // },
];
