export let serviciosMock = [
  {
    id: 1,
    title: "Envíos en 24 horas",
    description: "• Córdoba - Buenos Aires / Buenos Aires - Córdoba en 24hs.",
    description2: "• Frecuencia asegurada a más de 700 localidades del país.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",
    img: "./public/24hs.png",
  },
  {
    id: 2,
    title: "Ecommerce",
    description: "• Hacemos crecer tu emprendimiento.",
    description2: "• Paqueteria desde 100gr hasta 50kg.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",

    img: "./public/ecommerce.png",
  },
  {
    id: 3,
    title: "Cargas Completas",
    description: "• Equipos completos - 26 pallets.",
    description2: "• Chasis, acomplado, semiremolque y sider",
    description3: "• Entregas directas a clientes e interplantas",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "./public/cargasCompletas.png",
  },
  {
    id: 4,
    title: "Cargas Peligrosas",
    description:
      "• Conductores habilitados para transporte de cargas peligrosas.",
    description2:
      "• Vehículos con habilitación para transporte de cargas peligrosas.",
    description3:
      "• Agroquímicos, pinturas, químicos, inflamables, tóxicos y corrosivos.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "./public/cargasPeligrosas.png",
  },
  {
    id: 5,
    title: "Desconsolidado de Contenedores",
    description: "• Retiro de contenedor en puerto o aduana.",
    description2: "• Desconsolidado y palletizado de mercadería.",
    description3: "• Devolución de contenedor.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "./public/desconsolidado.png",
  },
  {
    id: 6,
    title: "Servicio Puerta a Puerta",
    description: "• Retiro a domicilio en Córdoba y Buenos Aires.",
    description2: "• Entrega a domicilio en mas de 700 localidades.",

    description3: "• Carga asegurada.",
    description4: "• Seguimiento online de tu envío.",

    description5: "• Atención humana y personalizada.",
    img: "./public/puerta.png",
  },
  {
    id: 7,
    title: "Warehouse",
    description: "• Almacenamiento de mercadería.",
    description2: "•Recepción de mercadería.",
    description3: "• Envío parcial de mercadería.",
    description4: "• Gestión de inventario.",
    description5: "• Fraccionamiento y repalletizado.",
    description6: "• Carga asegurada.",
    description7: "• Atención humana y personalizada.",
    img: "./public/warehouse.png",
  },
  // {
  //   id: 8,
  //   title: "Envíos a todo el país",
  //   description: "• Almacenamiento de mercadería.",
  //   description2: "•Recepción de mercadería.",
  //   description3: "• Envío parcial de mercadería.",
  //   description4: "• Gestión de inventario.",
  //   description5: "• Fraccionamiento y repalletizado.",
  //   description6: "• Carga asegurada.",
  //   description7: "• Atención humana y personalizada.",
  //   img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/mapa%20blanco.png?alt=media&token=299e5086-aae8-4787-a70b-117e7857dc3b",
  // },
];
