export let serviciosMock = [
  {
    id: 1,
    title: "Envíos en 24 horas",
    description: "• Córdoba - Buenos Aires / Buenos Aires - Córdoba en 24hs.",
    description2: "• Frecuencia asegurada a más de 700 localidades del país.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/24hs.png?alt=media&token=9e735313-404b-48a0-9b60-6158d4895a00",
  },
  {
    id: 2,
    title: "Ecommerce",
    description: "• Hacemos crecer tu emprendimiento.",
    description2: "• Paqueteria desde 100gr hasta 50kg.",
    description3: "• Retiro y entrega a domicilio.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Atención humana y personalizada.",

    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/ecommerce.png?alt=media&token=079b5a0f-1091-4e30-a07b-8d2e0aec3b21",
  },
  {
    id: 3,
    title: "Cargas Completas",
    description: "• Equipos completos - 26 pallets.",
    description2: "• Chasis, acomplado, semiremolque y sider",
    description3: "• Entregas directas a clientes e interplantas",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/cargasCompletas.png?alt=media&token=c8ad636f-7bb6-4db9-bcac-591e28b2c1d2",
  },
  {
    id: 4,
    title: "Cargas Peligrosas",
    description:
      "• Conductores habilitados para transporte de cargas peligrosas.",
    description2:
      "• Vehículos con habilitación para transporte de cargas peligrosas.",
    description3:
      "• Agroquímicos, pinturas, químicos, inflamables, tóxicos y corrosivos.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/cargasPeligrosas.png?alt=media&token=adf0e257-8bee-4962-a827-8dab9399ce13",
  },
  {
    id: 5,
    title: "Desconsolidado de Contenedores",
    description: "• Retiro de contenedor en puerto o aduana.",
    description2: "• Desconsolidado y palletizado de mercadería.",
    description3: "• Devolución de contenedor.",
    description4: "• Carga asegurada.",
    description5: "• Seguimiento online de tu envío.",
    description6: "• Monitoreo satelital.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/desconsolidado.png?alt=media&token=acf7d5ae-546b-4a82-8ae8-68ce73051df7",
  },
  {
    id: 6,
    title: "Servicio Puerta a Puerta",
    description: "• Retiro a domicilio en Córdoba y Buenos Aires.",
    description2: "• Entrega a domicilio en mas de 700 localidades.",

    description3: "• Carga asegurada.",
    description4: "• Seguimiento online de tu envío.",

    description5: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/puerta.png?alt=media&token=3d55225b-895e-4119-acf1-41453db412a3",
  },
  {
    id: 7,
    title: "Warehouse",
    description: "• Almacenamiento de mercadería.",
    description2: "•Recepción de mercadería.",
    description3: "• Envío parcial de mercadería.",
    description4: "• Gestión de inventario.",
    description5: "• Fraccionamiento y repalletizado.",
    description6: "• Carga asegurada.",
    description7: "• Atención humana y personalizada.",
    img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/warehouse.png?alt=media&token=876403fa-b19f-4b22-856a-94e60a0c53dc",
  },
  // {
  //   id: 8,
  //   title: "Envíos a todo el país",
  //   description: "• Almacenamiento de mercadería.",
  //   description2: "•Recepción de mercadería.",
  //   description3: "• Envío parcial de mercadería.",
  //   description4: "• Gestión de inventario.",
  //   description5: "• Fraccionamiento y repalletizado.",
  //   description6: "• Carga asegurada.",
  //   description7: "• Atención humana y personalizada.",
  //   img: "https://firebasestorage.googleapis.com/v0/b/logincor-f1fb5.appspot.com/o/mapa%20blanco.png?alt=media&token=299e5086-aae8-4787-a70b-117e7857dc3b",
  // },
];
